# Generated by Django 3.0.5 on 2020-07-29 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0046_auto_20200728_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbmi',
            name='bmdate',
            field=models.DateField(default=datetime.date(2020, 7, 29)),
        ),
    ]
